name: cs_smoke_app
description: A CS2 utility app.
publish_to: 'none'

version: 1.1.5+8

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  youtube_player_iframe: ^5.1.3
  bordered_text: ^2.0.0
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  share_plus: ^10.0.0
  url_launcher: ^6.1.14
  rate_my_app: ^2.0.0
  launch_app_store: ^1.0.2
  flutter_local_notifications: ^17.2.1+2
  rxdart: ^0.28.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_native_timezone_updated_gradle: ^2.0.3
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/img/maps/
    - assets/img/radar/
    - assets/img/callouts/
    - assets/img/map logo/
