name: cs_smoke_app
description: A CS2 utility app.
publish_to: 'none'

version: 1.1.2+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  youtube_player_iframe: ^4.0.4
  bordered_text: ^2.0.0
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  share_plus: ^7.2.0
  url_launcher: ^6.1.14
  rate_my_app: ^2.0.0
  launch_app_store: ^1.0.2
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_native_timezone_updated_gradle: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/img/maps/
    - assets/img/radar/
    - assets/img/map logo/
