name: cs_smoke_app
description: A CS2 utility app.
publish_to: 'none'

version: 1.1.6+9

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  youtube_player_iframe: ^5.2.1
  bordered_text: ^2.0.0
  firebase_core: ^3.12.0
  firebase_analytics: ^11.4.3
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  rate_my_app: ^2.3.1
  flutter_launch_store: ^1.0.8
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  flutter_timezone: ^4.1.0
  google_mobile_ads: ^5.3.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/img/maps/
    - assets/img/radar/
    - assets/img/callouts/
    - assets/img/map logo/
